services:
  db:
    image: 'wodby/mariadb:$MARIADB_TAG'
    container_name: db-ko0gk8ckkksokocoww0ws80s-134130755517
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      COOLIFY_BRANCH: '"d11"'
      COOLIFY_CONTAINER_NAME: '"db-ko0gk8ckkksokocoww0ws80s-134130755517"'
    volumes:
      - 'ko0gk8ckkksokocoww0ws80s_db:/var/lib/mysql'
    restart: unless-stopped
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.376
      - coolify.applicationId=11492
      - coolify.type=application
      - coolify.name=db-ko0gk8ckkksokocoww0ws80s-134130755517
      - coolify.pullRequestId=0
    networks:
      ko0gk8ckkksokocoww0ws80s: null
  php:
    container_name: php-ko0gk8ckkksokocoww0ws80s-134130789020
    build:
      context: .
      dockerfile: docker/php.dockerfile
      target: drupalbuilder
    environment:
      PHP_SENDMAIL_PATH: '/usr/sbin/sendmail -t -i -S mailhog:1025'
      DB_HOST: db
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_ROOT_PASSWORD: admin123
      DB_NAME: drupal
      DB_DRIVER: mysql
      COLUMNS: 80
      DOCROOT_SUBDIR: null
      WODBY_APP_SUBSITE: default
      HTTP_ROOT: /var/www/html/docroot
      APP_ROOT: /var/www/html
      CONF_DIR: /var/www/html/conf
      DRUPAL_VERSION: '11'
      DRUSH_OPTIONS_URI: '${COOLFIY_URL}'
      DRUPAL_SITE: default
      DRUPAL_SITE_DIR: /var/www/html/docroot/sites/default
      DRUPAL_HASH_SALT: bad-hash-salt-must-be-32-characters_long
      DRUPAL_FILES_SYNC_SALT: files-sync-bad-salt
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      WODBY_HOSTS: '["${COOLIFY_URL}"]'
      WODBY_PRIMARY_HOST: $COOLIFY_URL
      COOLFIY_URL: null
      COOLIFY_URL: null
      COOLIFY_BRANCH: '"d11"'
      COOLIFY_CONTAINER_NAME: '"php-ko0gk8ckkksokocoww0ws80s-134130789020"'
    networks:
      default: null
      ko0gk8ckkksokocoww0ws80s: null
    restart: unless-stopped
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.376
      - coolify.applicationId=11492
      - coolify.type=application
      - coolify.name=php-ko0gk8ckkksokocoww0ws80s-134130789020
      - coolify.pullRequestId=0
  nginx:
    container_name: nginx-ko0gk8ckkksokocoww0ws80s-134130817932
    build:
      context: .
      dockerfile: docker/php.dockerfile
      target: nginxbuilder
    networks:
      default: null
      ko0gk8ckkksokocoww0ws80s: null
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: 'off'
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/docroot
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
      NGINX_DRUPAL_FILE_PROXY_URL: $COOLIFY_URL
      COOLIFY_URL: 'https://tcg00s40ogow8g8osggw48k8.dev2.key-tec.de'
      COOLIFY_BRANCH: '"d11"'
      COOLIFY_CONTAINER_NAME: '"nginx-ko0gk8ckkksokocoww0ws80s-134130817932"'
      COOLIFY_FQDN: tcg00s40ogow8g8osggw48k8.dev2.key-tec.de
    labels:
      - traefik.enable=true
      - 'traefik.http.routers.$${PROJECT_NAME}_nginx.entrypoints=https'
      - 'traefik.http.routers.$${PROJECT_NAME}_nginx.rule=Host(`$${COOLIFY_URL}`)'
      - 'traefik.http.routers.$${PROJECT_NAME}_nginx.tls=true'
      - 'traefik.http.services.$${PROJECT_NAME}_nginx.loadbalancer.server.port=80'
      - 'traefik.http.routers.$${PROJECT_NAME}_nginx.service=$${PROJECT_NAME}_nginx@docker'
      - traefik.docker.network=traefik_proxy
      - coolify.managed=true
      - coolify.version=4.0.0-beta.376
      - coolify.applicationId=11492
      - coolify.type=application
      - coolify.name=nginx-ko0gk8ckkksokocoww0ws80s-134130817932
      - coolify.pullRequestId=0
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-ko0gk8ckkksokocoww0ws80s-nginx.entryPoints=http
      - traefik.http.routers.http-0-ko0gk8ckkksokocoww0ws80s-nginx.middlewares=redirect-to-https
      - 'traefik.http.routers.http-0-ko0gk8ckkksokocoww0ws80s-nginx.rule=Host(`tcg00s40ogow8g8osggw48k8.dev2.key-tec.de`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-ko0gk8ckkksokocoww0ws80s-nginx.entryPoints=https
      - traefik.http.routers.https-0-ko0gk8ckkksokocoww0ws80s-nginx.middlewares=gzip
      - 'traefik.http.routers.https-0-ko0gk8ckkksokocoww0ws80s-nginx.rule=Host(`tcg00s40ogow8g8osggw48k8.dev2.key-tec.de`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-ko0gk8ckkksokocoww0ws80s-nginx.tls.certresolver=letsencrypt
      - traefik.http.routers.https-0-ko0gk8ckkksokocoww0ws80s-nginx.tls=true
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams}}'
      - 'caddy_0.handle_path=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=https://tcg00s40ogow8g8osggw48k8.dev2.key-tec.de'
      - caddy_ingress_network=ko0gk8ckkksokocoww0ws80s
    restart: unless-stopped
  mailhog:
    image: mailhog/mailhog
    networks:
      default: null
      ko0gk8ckkksokocoww0ws80s: null
    container_name: mailhog-ko0gk8ckkksokocoww0ws80s-134130835562
    labels:
      - traefik.enable=true
      - 'traefik.http.routers.$${PROJECT_NAME}_mailhog.entrypoints=https'
      - 'traefik.http.routers.$${PROJECT_NAME}_mailhog.rule=Host(`$${COOLIFY_URL}`) && PathPrefix(`/mailhog`)'
      - 'traefik.http.middlewares.$${PROJECT_NAME}_mailhog.stripprefix.prefixes=/mailhog'
      - 'traefik.http.routers.$${PROJECT_NAME}_mailhog.middlewares=our-slash@docker'
      - 'traefik.http.routers.$${PROJECT_NAME}_mailhog.tls=true'
      - 'traefik.http.services.$${PROJECT_NAME}_mailhog.loadbalancer.server.port=8025'
      - 'traefik.http.routers.$${PROJECT_NAME}_mailhog.service=$${PROJECT_NAME}_mailhog@docker'
      - traefik.docker.network=traefik_proxy
      - coolify.managed=true
      - coolify.version=4.0.0-beta.376
      - coolify.applicationId=11492
      - coolify.type=application
      - coolify.name=mailhog-ko0gk8ckkksokocoww0ws80s-134130835562
      - coolify.pullRequestId=0
    restart: unless-stopped
    environment:
      COOLIFY_BRANCH: '"d11"'
      COOLIFY_CONTAINER_NAME: '"mailhog-ko0gk8ckkksokocoww0ws80s-134130835562"'
volumes:
  db:
    name: '${PROJECT_NAME}-db'
  ko0gk8ckkksokocoww0ws80s_db:
    name: ko0gk8ckkksokocoww0ws80s_db
networks:
  default:
    driver: bridge
  ko0gk8ckkksokocoww0ws80s:
    name: ko0gk8ckkksokocoww0ws80s
    driver: bridge
configs: {  }
secrets: {  }
