#!/usr/bin/env bash

ROOT_DIR="$(pwd)/"

echo "Executing .git/hooks/pre-push..."
ddev exec /var/www/html/vendor/bin/blt internal:git-hook:execute:pre-push

# Return the status of the last run command.
exit $?
