#!/bin/bash

## Description: Init Environment
## Usage: init
## Example: "ddev init"

ddev start

# Run composer install
ddev composer install

ddev exec --dir /var/www/html/ocroot/themes/custom '[ ! -d "wingsuit" ] && npx @wingsuit-designsystem/cli init -k tailwind --skip-install --branch=2.0.x; cd wingsuit && yarn install; yarn build:drupal'
# Import database
ddev import-db --file dump/dump.sql

ddev drush updb

# Clear Cache
ddev drush cr

# Run config imports


FULLURL=${DDEV_PRIMARY_URL}

printf "Welcome on Wingsuit! \n\n"
printf "Open $FULLURL \nLogin under ${FULLURL}/user/login\n"
printf "Login with: admin/admin\n\n"
