#!/bin/bash

## Description: Init Environment
## Usage: init
## Example: "ddev init"

ddev start

# Run composer install
ddev composer install

# Import database
ddev import-db --file dump/dump.sql

ddev drush updb

ddev drush cim

# Clear Cache
ddev drush cr

# Run config imports


FULLURL=${DDEV_PRIMARY_URL}

printf "Welcome on Wingsuit! \n\n"
printf "Open $FULLURL \nLogin under ${FULLURL}/user/login\n"
printf "Login with: admin/admin\n\n"
