<?php
use Drupal\Core\Form\FormStateInterface;
use Drupal\ui_patterns\Definition\PatternDefinition ;

/**
 * Fix Non-translatable fields can only be changed when updating the original language.
 *
 * Implements hook_entity_type_alter().
 */
function wingsuit_layout_entity_type_alter(array &$entity_types) {
  foreach ($entity_types as $entity_type) {
    $constraints = $entity_type->getConstraints();
    unset($constraints['EntityUntranslatableFields']);
    $entity_type->setConstraints($constraints);
  }
}
