<?php

use Drupal\layout_builder\Form\OverridesEntityForm;
use Drupal\layout_builder\Form\DefaultsEntityForm;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function wingsuit_layout_theme($existing, $type, $theme, $path) {
  return array(
    'form__node_landing_page_layout_builder_form' => array(
      'template' => 'form--node-landing-page-layout-builder-form',
      'base hook' => 'form'
    ),
  );
}

/**
 * Implements hook_form_alter().
 */
function wingsuit_layout_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form_object = $form_state->getFormObject();
  if ($form_object instanceof OverridesEntityForm || $form_object instanceof DefaultsEntityForm
    || $form_object->getFormId() === 'layout_layout_builder_form'
  ) {
    $form['#attached']['library'][] = 'wingsuit_layout/layout_builder';
  }
  $form['actions']['layout_overview']['#markup'] = '<div id="layout-overview-button" class="layout-overview-button button">' . t('Layout overview') . '</div>';
  $form['actions']['layout_overview']['#weight'] = 15;
  $form['actions']['moderation_state_toggler'] = [
    '#type' => 'checkbox',
    '#title' => t('Show moderation states'),
    '#weight' => 20,
    '#attributes' => [
      'class' => ['layout-builder-moderation-state'],
    ]
  ];
  $form['layout_builder_message']['#weight'] = -3000;
  $form['revision_information']['#prefix'] = '<div class="hidden">';
  $form['revision_information']['#suffix'] = '</div>';
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function wingsuit_layout_theme_suggestions_form_alter(array &$suggestions, array $variables) {
  $suggestions[] = 'form__' . $variables['element']['#form_id'];
}
